//
//  LLMStationTypes.swift
//  Curate
//
//  Types for LLM-generated music stations.
//  Designed for easy integration with Thompson Sampling later.
//

import Foundation

// MARK: - LLM Station Config
/// Configuration generated by LLM from user's natural language prompt.
/// This defines the "shape" of the station - what kind of music fits.
struct LLMStationConfig: Codable, Equatable {
    let name: String
    let description: String
    let originalPrompt: String
    
    // MARK: - Feature Targets (LLM's interpretation of the prompt)
    /// Target ranges for audio features (0-1 scale)
    /// These will be used by Thompson Sampling later
    let valenceRange: FeatureRangeLLM?       // Mood: 0=sad, 1=happy
    let energyRange: FeatureRangeLLM?        // 0=calm, 1=intense
    let danceabilityRange: FeatureRangeLLM?  // 0=still, 1=danceable
    let bpmRange: FeatureRangeLLM?           // Normalized 0-1 (60-200 BPM)
    let acousticnessRange: FeatureRangeLLM?  // 0=electronic, 1=acoustic
    let instrumentalnessRange: FeatureRangeLLM? // 0=vocals, 1=instrumental
    
    // MARK: - Feature Weights (how important each feature is)
    let valenceWeight: Float
    let energyWeight: Float
    let danceabilityWeight: Float
    let bpmWeight: Float
    let acousticnessWeight: Float
    let instrumentalnessWeight: Float
    
    // MARK: - Contextual Metadata
    let suggestedGenres: [String]
    let suggestedDecades: [Int]?
    let moodKeywords: [String]
    let contextDescription: String  // LLM's interpretation of the vibe
    
    // MARK: - Defaults
    static let `default` = LLMStationConfig(
        name: "My Station",
        description: "A personalized music station",
        originalPrompt: "",
        valenceRange: nil,
        energyRange: nil,
        danceabilityRange: nil,
        bpmRange: nil,
        acousticnessRange: nil,
        instrumentalnessRange: nil,
        valenceWeight: 1.0,
        energyWeight: 1.0,
        danceabilityWeight: 0.8,
        bpmWeight: 0.8,
        acousticnessWeight: 0.5,
        instrumentalnessWeight: 0.5,
        suggestedGenres: [],
        suggestedDecades: nil,
        moodKeywords: [],
        contextDescription: ""
    )
}

// MARK: - Feature Range (LLM version)
/// Represents a target range for a feature
struct FeatureRangeLLM: Codable, Equatable {
    let min: Float
    let max: Float
    
    var target: Float {
        (min + max) / 2
    }
    
    func contains(_ value: Float) -> Bool {
        value >= min && value <= max
    }
    
    /// Score how well a value fits this range (1.0 = perfect, 0.0 = far outside)
    func score(for value: Float) -> Float {
        if contains(value) {
            return 1.0
        } else if value < min {
            return Swift.max(0, 1.0 - (min - value))
        } else {
            return Swift.max(0, 1.0 - (value - self.max))
        }
    }
}

// MARK: - LLM Song Suggestion
/// A song suggested by the LLM, before verification
struct LLMSongSuggestion: Codable, Equatable, Identifiable {
    var id: String { "\(title)-\(artist)" }
    
    let title: String
    let artist: String
    let album: String?
    let year: Int?
    let reason: String  // Why LLM suggested this
    
    // MARK: - LLM-Estimated Audio Features
    /// These are the LLM's best guesses for audio features
    /// Will be used for Thompson Sampling until we get real data
    let estimatedBpm: Float?
    let estimatedEnergy: Float?
    let estimatedValence: Float?
    let estimatedDanceability: Float?
    let estimatedAcousticness: Float?
    let estimatedInstrumentalness: Float?
    
    // MARK: - Verification Status
    var verificationStatus: VerificationStatus = .pending
    var appleMusicId: String?
    var isrc: String?
    var artworkURL: String?
    
    enum VerificationStatus: String, Codable {
        case pending
        case verified      // Found in Apple Music
        case notFound      // Could not find
        case playing       // Currently playing
        case played        // Already played
    }
    
    // MARK: - Convert to TrackFeatures for Thompson Sampling
    /// Creates a TrackFeatures from LLM estimates (for future Thompson Sampling)
    func toEstimatedFeatures() -> TrackFeatures {
        TrackFeatures(
            bpm: normalizedBpm,
            energy: estimatedEnergy ?? 0.5,
            danceability: estimatedDanceability ?? 0.5,
            valence: estimatedValence ?? 0.5,
            acousticness: estimatedAcousticness ?? 0.5,
            instrumentalness: estimatedInstrumentalness ?? 0.5
        )
    }
    
    /// Normalize BPM to 0-1 scale (assuming 60-200 BPM range)
    private var normalizedBpm: Float {
        guard let bpm = estimatedBpm else { return 0.5 }
        let minBPM: Float = 60
        let maxBPM: Float = 200
        return max(0, min(1, (bpm - minBPM) / (maxBPM - minBPM)))
    }
}

// MARK: - LLM Taste Profile
/// Evolving understanding of user's taste, derived from feedback
/// This will be sent to LLM for better suggestions over time
struct LLMTasteProfile: Codable, Equatable {
    var preferredGenres: [String]
    var avoidedGenres: [String]
    var preferredArtists: [String]
    var avoidedArtists: [String]
    var preferredDecades: [Int]
    var energyPreference: String  // "low", "medium", "high", "varied"
    var moodPreference: String    // "happy", "melancholic", "intense", "calm", "varied"
    var notablePatterns: [String] // e.g., "prefers female vocals", "likes guitar solos"
    
    var lastUpdatedAt: Date
    var feedbackCountAtUpdate: Int
    
    static let empty = LLMTasteProfile(
        preferredGenres: [],
        avoidedGenres: [],
        preferredArtists: [],
        avoidedArtists: [],
        preferredDecades: [],
        energyPreference: "varied",
        moodPreference: "varied",
        notablePatterns: [],
        lastUpdatedAt: Date(),
        feedbackCountAtUpdate: 0
    )
}

// MARK: - LLM Station Queue Item
/// A song in the station's play queue with all necessary data
struct LLMQueueItem: Identifiable, Equatable {
    let id: UUID
    let suggestion: LLMSongSuggestion
    var appleMusicId: String?
    var isrc: String?
    var artworkURL: URL?
    var status: PlayStatus
    
    enum PlayStatus: Equatable {
        case queued
        case playing
        case played
        case skipped
        case failed(String)  // Error message
    }
    
    init(suggestion: LLMSongSuggestion) {
        self.id = UUID()
        self.suggestion = suggestion
        self.appleMusicId = suggestion.appleMusicId
        self.isrc = suggestion.isrc
        self.status = .queued
        if let urlString = suggestion.artworkURL {
            self.artworkURL = URL(string: urlString)
        }
    }
}

// MARK: - LLM Request/Response Types
/// Request structure for generating station config
struct LLMConfigRequest {
    let prompt: String
    let existingTasteProfile: LLMTasteProfile?
}

/// Request structure for getting song suggestions
struct LLMSongRequest {
    let config: LLMStationConfig
    let likedSongs: [LikedSongInfo]
    let dislikedSongs: [DislikedSongInfo]
    let recentlyPlayed: [String]  // Song titles to avoid
    let count: Int
    
    struct LikedSongInfo: Codable {
        let title: String
        let artist: String
    }
    
    struct DislikedSongInfo: Codable {
        let title: String
        let artist: String
    }
}

// MARK: - Station Feedback Summary
/// Summary of feedback for a station, used in LLM prompts
struct StationFeedbackSummary: Codable {
    let totalLikes: Int
    let totalDislikes: Int
    let totalSkips: Int
    let likedSongs: [SongInfo]
    let dislikedSongs: [SongInfo]
    
    struct SongInfo: Codable {
        let title: String
        let artist: String
        let genre: String?
    }
    
    static let empty = StationFeedbackSummary(
        totalLikes: 0,
        totalDislikes: 0,
        totalSkips: 0,
        likedSongs: [],
        dislikedSongs: []
    )
}

// MARK: - Recommendation Strategy (for future Thompson Sampling)
/// Defines how songs should be selected
/// This abstraction allows swapping LLM-only for Thompson Sampling later
protocol RecommendationStrategy {
    func selectNext(
        from candidates: [LLMSongSuggestion],
        feedbackHistory: StationFeedbackSummary,
        temperature: Float
    ) -> LLMSongSuggestion?
}

/// Simple strategy: just pick the next unplayed song
/// Will be replaced with Thompson Sampling later
struct SimpleSequentialStrategy: RecommendationStrategy {
    func selectNext(
        from candidates: [LLMSongSuggestion],
        feedbackHistory: StationFeedbackSummary,
        temperature: Float
    ) -> LLMSongSuggestion? {
        // For now, just return the first unplayed song
        candidates.first { $0.verificationStatus == .verified }
    }
}

/// Placeholder for future Thompson Sampling strategy
struct ThompsonSamplingStrategy: RecommendationStrategy {
    let parameters: ThompsonParameters

    func selectNext(
        from candidates: [LLMSongSuggestion],
        feedbackHistory: StationFeedbackSummary,
        temperature: Float
    ) -> LLMSongSuggestion? {
        // TODO: Implement Thompson Sampling based selection
        // For now, fall back to sequential
        return SimpleSequentialStrategy().selectNext(
            from: candidates,
            feedbackHistory: feedbackHistory,
            temperature: temperature
        )
    }
}

// MARK: - Artist Seed Request/Response Types

/// Request for generating artist seeds from LLM
struct LLMArtistSeedRequest: Codable {
    let config: LLMStationConfig
    let tasteSummary: String?
    let avoidArtists: [String]?
    let count: Int
}

/// Response from artist seed generation
struct LLMArtistSeedResponse: Codable {
    let seeds: [ArtistSeedInfo]

    struct ArtistSeedInfo: Codable {
        let name: String
        let reason: String
        let similarityType: String
        let expectedGenres: [String]?
    }
}

// MARK: - Station Config Extension for Hashing

extension LLMStationConfig {
    /// Generate a stable hash for caching purposes
    var configHash: String {
        var components: [String] = []
        components.append("name:\(name)")
        components.append("desc:\(description)")
        components.append("prompt:\(originalPrompt)")

        if !suggestedGenres.isEmpty {
            components.append("genres:\(suggestedGenres.sorted().joined(separator: ","))")
        }
        if let decades = suggestedDecades, !decades.isEmpty {
            components.append("decades:\(decades.sorted().map { String($0) }.joined(separator: ","))")
        }
        if !moodKeywords.isEmpty {
            components.append("keywords:\(moodKeywords.sorted().joined(separator: ","))")
        }

        // Include ranges if set
        if let energy = energyRange {
            components.append("energy:\(energy.min)-\(energy.max)")
        }
        if let valence = valenceRange {
            components.append("valence:\(valence.min)-\(valence.max)")
        }

        let combined = components.joined(separator: "|")
        return combined.sha256Hash
    }
}

// MARK: - String SHA256 Extension

import CommonCrypto

extension String {
    /// Generate SHA256 hash of the string
    var sha256Hash: String {
        guard let data = self.data(using: .utf8) else { return self }
        var hash = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
        data.withUnsafeBytes {
            _ = CC_SHA256($0.baseAddress, CC_LONG(data.count), &hash)
        }
        return hash.map { String(format: "%02x", $0) }.joined()
    }
}
