//
//  HeuristicPoolTypes.swift
//  Curate
//
//  Data models for the heuristic pool recommendation engine.
//  Enables on-device intent parsing without LLM calls.
//

import Foundation
import CryptoKit

// MARK: - Mood Categories

/// Primary mood categories extracted from user input
enum MoodCategory: String, CaseIterable, Codable, Hashable {
    case energetic
    case relaxed
    case melancholic
    case uplifting
    case aggressive
    case romantic
    case nostalgic
    case focused
    case party
    case chill
    case dreamy
    case intense
    case peaceful
    case groovy
    case dark

    /// Search-friendly term for this mood
    var searchTerm: String {
        switch self {
        case .energetic: return "energetic"
        case .relaxed: return "relaxed"
        case .melancholic: return "sad"
        case .uplifting: return "uplifting"
        case .aggressive: return "intense"
        case .romantic: return "romantic"
        case .nostalgic: return "throwback"
        case .focused: return "focus"
        case .party: return "party"
        case .chill: return "chill"
        case .dreamy: return "dreamy"
        case .intense: return "intense"
        case .peaceful: return "peaceful"
        case .groovy: return "groovy"
        case .dark: return "dark"
        }
    }
}

// MARK: - Activity Context

/// Activity context detected from user input
enum ActivityContext: String, CaseIterable, Codable, Hashable {
    case driving
    case workout
    case studying
    case sleeping
    case cooking
    case working
    case commuting
    case party
    case dinner
    case meditation
    case running
    case yoga
    case gaming
    case cleaning
    case reading

    /// Search-friendly term for this activity
    var searchTerm: String {
        switch self {
        case .driving: return "driving"
        case .workout: return "workout"
        case .studying: return "study"
        case .sleeping: return "sleep"
        case .cooking: return "cooking"
        case .working: return "work"
        case .commuting: return "commute"
        case .party: return "party"
        case .dinner: return "dinner"
        case .meditation: return "meditation"
        case .running: return "running"
        case .yoga: return "yoga"
        case .gaming: return "gaming"
        case .cleaning: return "cleaning"
        case .reading: return "reading"
        }
    }
}

// MARK: - Time Context

/// Time-of-day context detected from user input
enum TimeContext: String, CaseIterable, Codable, Hashable {
    case morning
    case afternoon
    case evening
    case night
    case lateNight

    /// Search-friendly term for this time context
    var searchTerm: String {
        switch self {
        case .morning: return "morning"
        case .afternoon: return "afternoon"
        case .evening: return "evening"
        case .night: return "night"
        case .lateNight: return "late night"
        }
    }
}

// MARK: - Parsed Vibe

/// Output from the VibeParser - represents the parsed intent from user input
struct ParsedVibe: Equatable {
    let rawInput: String
    let moods: [MoodCategory]
    let activity: ActivityContext?
    let timeContext: TimeContext?
    let confidence: Float  // 0-1, for fallback decisions

    /// Canonical intent string for caching (hash of normalized components)
    var canonicalIntent: String {
        var components: [String] = []

        // Add sorted moods for consistency
        components.append(contentsOf: moods.map { $0.rawValue }.sorted())

        if let activity = activity {
            components.append("activity:\(activity.rawValue)")
        }

        if let time = timeContext {
            components.append("time:\(time.rawValue)")
        }

        let combined = components.joined(separator: "-")
        return combined.isEmpty ? "generic-vibe" : combined
    }

    /// Hash for pool lookups
    var intentHash: String {
        canonicalIntent.sha256Hash
    }

    /// Check if this is a low-confidence parse that might need fallback
    var needsFallback: Bool {
        confidence < 0.4 || moods.isEmpty
    }

    // MARK: - Factory Methods

    static func empty(input: String) -> ParsedVibe {
        ParsedVibe(
            rawInput: input,
            moods: [],
            activity: nil,
            timeContext: nil,
            confidence: 0.0
        )
    }
}

// MARK: - Heuristic Search Query

/// A search query generated by the SearchExpander
struct HeuristicSearchQuery: Equatable {
    let term: String
    let priority: Int
    let hasGenre: Bool
    let sourceRule: String  // Which expansion rule generated this

    /// Convert to PlaylistSearch for compatibility with existing types
    func toPlaylistSearch() -> PlaylistSearch {
        PlaylistSearch(term: term, priority: priority)
    }
}

// MARK: - Scored Playlist

/// A playlist scored against a parsed vibe
struct ScoredPlaylist {
    let playlist: ProviderPlaylist
    let moodScore: Float       // 0-1 based on keyword matches
    let genreScore: Float      // 0-1 based on genre matches
    let editorialBonus: Float  // 0.2 if editorial, 0 otherwise
    let totalScore: Float      // Combined weighted score

    /// Description for debugging
    var debugDescription: String {
        "[\(String(format: "%.2f", totalScore))] \(playlist.name) " +
        "(mood: \(String(format: "%.2f", moodScore)), " +
        "genre: \(String(format: "%.2f", genreScore)), " +
        "editorial: \(editorialBonus > 0 ? "yes" : "no"))"
    }
}

// MARK: - Recommendation Engine Enum

/// Available recommendation engines for A/B testing
enum RecommendationEngine: String, CaseIterable, Codable {
    case artistSeeds = "artistSeeds"
    case hybridPool = "hybridPool"
    case heuristicPool = "heuristicPool"
    case toolCalling = "toolCalling"

    var displayName: String {
        switch self {
        case .artistSeeds: return "Artist Seeds"
        case .hybridPool: return "Hybrid Pool (LLM)"
        case .heuristicPool: return "Heuristic Pool"
        case .toolCalling: return "AI Tool Calling"
        }
    }

    var description: String {
        switch self {
        case .artistSeeds:
            return "Uses LLM to generate artist seeds, then fetches top tracks"
        case .hybridPool:
            return "Uses LLM to parse intent, builds pool from playlists"
        case .heuristicPool:
            return "On-device parsing, genre-aware playlist search"
        case .toolCalling:
            return "LLM autonomously calls MusicKit tools to build stations"
        }
    }
}

// MARK: - Feature Flag

/// Feature flag for recommendation engine selection
enum RecommendationEngineFlag {
    private static let key = "recommendationEngine"

    static var current: RecommendationEngine {
        get {
            let raw = UserDefaults.standard.string(forKey: key) ?? ""
            return RecommendationEngine(rawValue: raw) ?? .toolCalling
        }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: key)
        }
    }

    static var isHeuristicPoolEnabled: Bool {
        current == .heuristicPool
    }

    static var isHybridPoolEnabled: Bool {
        current == .hybridPool
    }

    static var isArtistSeedsEnabled: Bool {
        current == .artistSeeds
    }

    static var isToolCallingEnabled: Bool {
        current == .toolCalling
    }
}

// MARK: - Keyword Mappings (Loaded from JSON)

/// Mood keyword mappings loaded from MoodKeywords.json
struct MoodKeywordMappings: Codable {
    let mappings: [String: [String]]

    /// Get keywords for a mood category
    func keywords(for mood: MoodCategory) -> [String] {
        mappings[mood.rawValue] ?? []
    }

    /// Find mood categories that match any of the given tokens
    func matchingMoods(for tokens: [String]) -> [(MoodCategory, Int)] {
        var results: [(MoodCategory, Int)] = []

        for mood in MoodCategory.allCases {
            let keywords = self.keywords(for: mood)
            let matchCount = tokens.filter { token in
                keywords.contains { keyword in
                    token.contains(keyword) || keyword.contains(token)
                }
            }.count

            if matchCount > 0 {
                results.append((mood, matchCount))
            }
        }

        return results.sorted { $0.1 > $1.1 }
    }

    /// Load from bundled JSON
    static func loadFromBundle() -> MoodKeywordMappings {
        guard let url = Bundle.main.url(forResource: "MoodKeywords", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let mappings = try? JSONDecoder().decode([String: [String]].self, from: data) else {
            print("⚠️ Failed to load MoodKeywords.json, using defaults")
            return MoodKeywordMappings(mappings: defaultMoodKeywords)
        }
        return MoodKeywordMappings(mappings: mappings)
    }

    /// Default mappings if JSON fails to load
    private static let defaultMoodKeywords: [String: [String]] = [
        "relaxed": ["chill", "calm", "peaceful", "mellow", "soothing", "laid back", "easy", "relax"],
        "energetic": ["upbeat", "hype", "pump", "high energy", "intense", "powerful", "energetic", "energy"],
        "melancholic": ["sad", "emotional", "heartbreak", "moody", "dark", "somber", "melancholy"],
        "uplifting": ["happy", "joyful", "positive", "feel good", "optimistic", "bright", "uplift"],
        "focused": ["study", "concentration", "work", "productive", "ambient", "minimal", "focus"],
        "party": ["dance", "club", "turnt", "lit", "celebration", "fun", "party"],
        "romantic": ["love", "sensual", "intimate", "date night", "smooth", "romantic"],
        "nostalgic": ["throwback", "retro", "classic", "old school", "memories", "90s", "80s", "nostalgia"],
        "chill": ["chill", "vibes", "lofi", "lo-fi", "ambient", "easy listening"],
        "aggressive": ["aggressive", "hard", "heavy", "rage", "angry", "intense"],
        "dreamy": ["dreamy", "ethereal", "atmospheric", "spacey", "floating"],
        "intense": ["intense", "epic", "dramatic", "cinematic", "powerful"],
        "peaceful": ["peaceful", "serene", "tranquil", "quiet", "gentle"],
        "groovy": ["groovy", "funky", "groove", "bass", "rhythm"],
        "dark": ["dark", "moody", "brooding", "noir", "gothic"]
    ]
}

/// Genre synonym mappings for normalization
struct GenreSynonymMappings: Codable {
    let mappings: [String: [String]]

    /// Normalize a genre string to its canonical form
    func normalize(_ genre: String) -> String {
        let lowercased = genre.lowercased()

        for (canonical, synonyms) in mappings {
            if canonical.lowercased() == lowercased {
                return canonical
            }
            if synonyms.contains(where: { $0.lowercased() == lowercased }) {
                return canonical
            }
        }

        return genre
    }

    /// Check if a text contains any genre or its synonyms
    func containsGenre(_ genre: String, in text: String) -> Bool {
        let lowercasedText = text.lowercased()
        let lowercasedGenre = genre.lowercased()

        // Direct match
        if lowercasedText.contains(lowercasedGenre) {
            return true
        }

        // Synonym match
        if let synonyms = mappings[genre] ?? mappings.first(where: { $0.key.lowercased() == lowercasedGenre })?.value {
            return synonyms.contains { lowercasedText.contains($0.lowercased()) }
        }

        return false
    }

    /// Load from bundled JSON
    static func loadFromBundle() -> GenreSynonymMappings {
        guard let url = Bundle.main.url(forResource: "GenreSynonyms", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let mappings = try? JSONDecoder().decode([String: [String]].self, from: data) else {
            print("⚠️ Failed to load GenreSynonyms.json, using defaults")
            return GenreSynonymMappings(mappings: defaultGenreSynonyms)
        }
        return GenreSynonymMappings(mappings: mappings)
    }

    /// Default mappings if JSON fails to load
    private static let defaultGenreSynonyms: [String: [String]] = [
        "Hip-Hop": ["hip hop", "hiphop", "rap", "trap", "boom bap"],
        "R&B": ["rnb", "r and b", "rhythm and blues", "soul"],
        "Electronic": ["edm", "house", "techno", "trance", "dubstep", "electronic"],
        "Rock": ["alternative rock", "indie rock", "hard rock", "rock"],
        "Pop": ["top 40", "mainstream", "chart", "pop"],
        "Jazz": ["smooth jazz", "bebop", "jazz fusion", "jazz"],
        "Classical": ["orchestra", "symphony", "chamber music", "classical"],
        "Country": ["country", "americana", "bluegrass"],
        "Metal": ["metal", "heavy metal", "death metal", "metalcore"],
        "Folk": ["folk", "acoustic", "singer-songwriter"],
        "Blues": ["blues", "delta blues", "chicago blues"],
        "Reggae": ["reggae", "dancehall", "dub"],
        "Latin": ["latin", "reggaeton", "salsa", "bachata"],
        "Indie": ["indie", "independent", "alternative"],
        "Alternative": ["alternative", "alt", "indie rock"]
    ]
}

// MARK: - Activity Keywords

/// Activity detection keywords
struct ActivityKeywords {
    static let mappings: [ActivityContext: [String]] = [
        .driving: ["drive", "driving", "road trip", "car", "highway", "cruise"],
        .workout: ["workout", "gym", "exercise", "training", "lift", "pump"],
        .studying: ["study", "studying", "homework", "exam", "learn"],
        .sleeping: ["sleep", "sleeping", "bedtime", "lullaby", "rest"],
        .cooking: ["cooking", "kitchen", "baking", "dinner prep"],
        .working: ["work", "working", "office", "productive", "focus"],
        .commuting: ["commute", "commuting", "subway", "train", "bus"],
        .party: ["party", "parties", "celebration", "birthday", "gathering"],
        .dinner: ["dinner", "dining", "restaurant", "date night", "meal"],
        .meditation: ["meditation", "meditate", "mindfulness", "zen", "breathing"],
        .running: ["running", "run", "jogging", "jog", "sprint"],
        .yoga: ["yoga", "stretch", "stretching", "flexibility"],
        .gaming: ["gaming", "game", "video games", "streaming"],
        .cleaning: ["cleaning", "clean", "chores", "housework"],
        .reading: ["reading", "read", "book", "library"]
    ]

    /// Find activity that matches the given tokens
    static func matchingActivity(for tokens: [String]) -> ActivityContext? {
        for (activity, keywords) in mappings {
            for keyword in keywords {
                if tokens.contains(where: { $0.contains(keyword) || keyword.contains($0) }) {
                    return activity
                }
            }
        }
        return nil
    }
}

// MARK: - Time Context Keywords

/// Time context detection keywords
struct TimeContextKeywords {
    static let mappings: [TimeContext: [String]] = [
        .morning: ["morning", "sunrise", "wake up", "breakfast", "am"],
        .afternoon: ["afternoon", "midday", "lunch"],
        .evening: ["evening", "sunset", "dusk", "golden hour"],
        .night: ["night", "nighttime", "after dark", "pm"],
        .lateNight: ["late night", "midnight", "3am", "after hours", "insomnia"]
    ]

    /// Find time context that matches the given tokens
    static func matchingTimeContext(for tokens: [String]) -> TimeContext? {
        let joinedInput = tokens.joined(separator: " ")

        for (context, keywords) in mappings {
            for keyword in keywords {
                if joinedInput.contains(keyword) {
                    return context
                }
            }
        }
        return nil
    }
}
